INSERT INTO "TransactionType" (
    "id",
    "code",
    "name",
    "description",
    "level",
    "category",
    "baseFee",
    "deliveryFee",
    "isFixed",
    "requiresBusinessName",
    "supportsECopy",
    "requiredDocs",
    "formSchema",
    "slaDays",
    "isActive",
    "createdAt",
    "updatedAt"
)
VALUES (
    'occupancy_permit_type',
    'OCCUPANCY_PERMIT',
    'Occupancy Permit',
    'Apply for and process an occupancy permit.',
    1,
    'Occupancy Permit',
    1000,
    100,
    FALSE,
    FALSE,
    TRUE,
    '["Valid ID", "Proof of Ownership", "Building Permit", "Certificate of Completion", "Fire Safety Inspection Certificate"]'::jsonb,
    '{"type":"OCCUPANCY_PERMIT","fields":[]}'::jsonb,
    3,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("code") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "level" = EXCLUDED."level",
    "category" = EXCLUDED."category",
    "baseFee" = EXCLUDED."baseFee",
    "deliveryFee" = EXCLUDED."deliveryFee",
    "isFixed" = EXCLUDED."isFixed",
    "requiresBusinessName" = EXCLUDED."requiresBusinessName",
    "supportsECopy" = EXCLUDED."supportsECopy",
    "requiredDocs" = EXCLUDED."requiredDocs",
    "formSchema" = EXCLUDED."formSchema",
    "slaDays" = EXCLUDED."slaDays",
    "isActive" = EXCLUDED."isActive",
    "updatedAt" = CURRENT_TIMESTAMP;
