import { Dispatch, SetStateAction } from "react";

export interface TreasuryViewProps {
    transaction: any;
    session: any;
    userRole: string;
    rawUserRole: string;
    isTreasuryStaff: boolean;
    isBPLOAdmin: boolean;
    isReadOnlyAide: boolean;
    backUrl: string;
    actionLoading: boolean;
    setActionLoading: Dispatch<SetStateAction<boolean>>;
    remarks: string;
    setRemarks: Dispatch<SetStateAction<string>>;
    ctcNumber: string;
    setCtcNumber: Dispatch<SetStateAction<string>>;
    stickerNumber: string;
    setStickerNumber: Dispatch<SetStateAction<string>>;
    isRejecting: boolean;
    setIsRejecting: Dispatch<SetStateAction<boolean>>;
    isRequestingRevision: boolean;
    setIsRequestingRevision: Dispatch<SetStateAction<boolean>>;
    deliveryFee: number;
    setDeliveryFee: Dispatch<SetStateAction<number>>;
    eCopyFile: File | null;
    setECopyFile: Dispatch<SetStateAction<File | null>>;
    eCopyPreview: string | null;
    setECopyPreview: Dispatch<SetStateAction<string | null>>;
    orFile: File | null;
    setOrFile: Dispatch<SetStateAction<File | null>>;
    orPreview: string | null;
    setOrPreview: Dispatch<SetStateAction<string | null>>;
    receiptFile: File | null;
    setReceiptFile: Dispatch<SetStateAction<File | null>>;
    receiptPreview: string | null;
    setReceiptPreview: Dispatch<SetStateAction<string | null>>;
    handleReceiptFileSelect: (e: React.ChangeEvent<HTMLInputElement>) => void;
    themeColor: string;
    branding: {
        word1: string;
        word2: string;
        logo: string;
    };
    additionalFeeLabel: string;
    setAdditionalFeeLabel: Dispatch<SetStateAction<string>>;
    additionalFeeAmount: string;
    setAdditionalFeeAmount: Dispatch<SetStateAction<string>>;
    showAdditionalFeeForm: boolean;
    setShowAdditionalFeeForm: Dispatch<SetStateAction<boolean>>;
    isResolvingDispute: boolean;
    setIsResolvingDispute: Dispatch<SetStateAction<boolean>>;
    disputeModalOpen: boolean;
    setDisputeModalOpen: Dispatch<SetStateAction<boolean>>;
    disputeAction: "APPROVE" | "REJECT";
    setDisputeAction: Dispatch<SetStateAction<"APPROVE" | "REJECT">>;
    showPreviousPhases: boolean;
    setShowPreviousPhases: Dispatch<SetStateAction<boolean>>;
    feeLineItems: { label: string; amount: string; readonly?: boolean }[];
    setFeeLineItems: Dispatch<SetStateAction<{ label: string; amount: string; readonly?: boolean }[]>>;
    fetchTransaction: () => Promise<void>;
    handleEvaluate: () => Promise<void>;
    handleConfirmPayment: () => Promise<void>;
    handleDeclinePaymentProof: () => Promise<void>;
    handlePrintWaybill: () => void;
    handleRelease: () => Promise<void>;
    handleResolveDispute: () => Promise<void>;
    handleAddAdditionalFee: () => Promise<void>;
    handleRemoveAdditionalFee: (index: number) => Promise<void>;
    handleApproveBilling: () => Promise<void>;
    handleReject: () => Promise<void>;
    handleRequestRevision: () => Promise<void>;
    addFeeLineItem: () => void;
    removeFeeLineItem: (index: number) => void;
    updateFeeLineItem: (index: number, field: "label" | "amount", value: string) => void;
    safeFormatDate: (dateStr: any) => string;
    declaredValue: number | string;
    declaredLabel: string;
    calcResult: any;
    displayTotal: number;
    evidenceDocs: { url?: string | null; label: string }[];
    steps: { id: string; label: string }[];
    currentStepIdx: number;
    hasVerification: boolean;
    hasDispute: boolean;
    isRequirementsAlone: boolean;
    handleViewFile?: (url: string | null, title: string, docs?: { url?: string | null; label: string }[], index?: number) => void;
    registryBookVerification?: string;
    setRegistryBookVerification?: Dispatch<SetStateAction<string>>;
    birthRegDocFile?: File | null;
    setBirthRegDocFile?: Dispatch<SetStateAction<File | null>>;
    birthRegDocPreview?: string | null;
    setBirthRegDocPreview?: Dispatch<SetStateAction<string | null>>;
    orSeriesNumber?: string;
    setOrSeriesNumber?: Dispatch<SetStateAction<string>>;
    miscFee?: string;
    setMiscFee?: Dispatch<SetStateAction<string>>;
    handleProcessRequest?: () => Promise<void>;
    handleOnsitePayment?: (method: string, amountTendered?: number) => Promise<void>;
}
