import lguConfig from "@/config/lgu.config.json";

export const configuredBarangays = lguConfig.barangays.filter((name) => !name.includes("{{"));
export const lguMapCenter: [number, number] = [
    lguConfig.map.latitude ?? 0,
    lguConfig.map.longitude ?? 0,
];
export const lguMapCenterLngLat: [number, number] = [lguMapCenter[1], lguMapCenter[0]];

const templateValues: Record<string, string> = {
    "{{LGU_NAME}}": lguConfig.identity.name,
    "{{LGU_FULL_NAME}}": lguConfig.identity.fullName,
    "{{PROVINCE_NAME}}": lguConfig.identity.province,
    "{{REGION_NAME}}": lguConfig.identity.region,
    "{{LGU_DEMONYM}}": lguConfig.identity.demonym,
    "{{LGU_TAGLINE}}": lguConfig.identity.tagline,
    "{{LGU_WEBSITE_URL}}": lguConfig.identity.website,
    "{{MAYOR_NAME}}": lguConfig.officials.mayor,
    "{{VICE_MAYOR_NAME}}": lguConfig.officials.viceMayor,
    "{{DATA_PRIVACY_OFFICER}}": lguConfig.officials.dataPrivacyOfficer,
    "{{MUNICIPAL_ADDRESS}}": lguConfig.contact.address,
    "{{LGU_EMAIL}}": lguConfig.contact.email,
    "{{LGU_PHONE}}": lguConfig.contact.phone,
    "{{LGU_FAX}}": lguConfig.contact.fax,
    "{{OFFICE_HOURS}}": lguConfig.contact.officeHours,
    "{{POLICE_HOTLINE}}": lguConfig.contact.hotlines.police,
    "{{FIRE_HOTLINE}}": lguConfig.contact.hotlines.fire,
    "{{HEALTH_HOTLINE}}": lguConfig.contact.hotlines.health,
    "{{HEALTH_OFFICER_HOTLINE}}": lguConfig.contact.hotlines.healthOfficer,
    "{{DISASTER_RESPONSE_HOTLINE}}": lguConfig.contact.hotlines.disasterResponse,
    "{{LGU_FACEBOOK_URL}}": lguConfig.social.facebook,
    "{{LGU_INSTAGRAM_URL}}": lguConfig.social.instagram,
    "{{LGU_YOUTUBE_URL}}": lguConfig.social.youtube,
    "{{POSO_FACEBOOK_URL}}": lguConfig.social.posoFacebook,
    "{{GOOGLE_PLAY_URL}}": lguConfig.apps.googlePlayUrl,
    "{{APP_STORE_URL}}": lguConfig.apps.appStoreUrl,
    "{{LGU_APP_APK_URL}}": lguConfig.apps.apkDownloadUrl,
    "{{GCASH_ACCOUNT_NAME}}": lguConfig.payments.gcashAccountName,
    "{{GCASH_ACCOUNT_NUMBER}}": lguConfig.payments.gcashAccountNumber,
    "{{BANK_NAME}}": lguConfig.payments.bankName,
    "{{BANK_ACCOUNT_NAME}}": lguConfig.payments.bankAccountName,
    "{{BANK_ACCOUNT_NUMBER}}": lguConfig.payments.bankAccountNumber,
    "{{POSO_ADDRESS}}": lguConfig.poso.address,
    "{{POSO_HOTLINE}}": lguConfig.poso.hotline,
    "{{POSO_OFFICE_HOURS}}": lguConfig.poso.officeHours,
    "{{POSO_EMAIL}}": lguConfig.poso.email,
    "{{LGU_HISTORY}}": lguConfig.about.history,
    "{{LGU_MISSION}}": lguConfig.about.mission,
    "{{LGU_VISION}}": lguConfig.about.vision,
    "{{LGU_CORE_VALUES}}": lguConfig.about.coreValues,
    "{{LGU_GEOGRAPHY_OR_DEMOGRAPHICS}}": lguConfig.about.geographyOrDemographics,
    "{{MAYOR_MESSAGE}}": lguConfig.about.mayorMessage,
    "{{ADMIN_EMAIL}}": lguConfig.seedAccounts.adminEmail,
    "{{BPLO_EMAIL}}": lguConfig.seedAccounts.bploEmail,
    "{{TREASURY_EMAIL}}": lguConfig.seedAccounts.treasuryEmail,
    "{{ADMIN_AIDE_EMAIL}}": lguConfig.seedAccounts.adminAideEmail,
    "{{RIDER_EMAIL}}": lguConfig.seedAccounts.riderEmail,
    "{{RHU_EMAIL}}": lguConfig.seedAccounts.rhuEmail,
    "{{MAIN_RHU_EMAIL}}": lguConfig.seedAccounts.mainRhuEmail,
    "{{RHU_MEDICAL_STAFF_EMAIL}}": lguConfig.seedAccounts.rhuMedicalStaffEmail,
    "{{RHU_DOCTOR_EMAIL}}": lguConfig.seedAccounts.rhuDoctorEmail,
    "{{ASSESSOR_EMAIL}}": lguConfig.seedAccounts.assessorEmail,
    "{{DISASTER_RESPONSE_EMAIL}}": lguConfig.seedAccounts.disasterResponseEmail,
    "{{RESIDENT_EMAIL}}": lguConfig.seedAccounts.residentEmail,
    "{{MARKET_VENDOR_1_EMAIL}}": lguConfig.seedAccounts.marketVendor1Email,
    "{{MARKET_VENDOR_2_EMAIL}}": lguConfig.seedAccounts.marketVendor2Email,
    "{{MARKET_VENDOR_3_EMAIL}}": lguConfig.seedAccounts.marketVendor3Email,
    "{{MARKET_VENDOR_4_EMAIL}}": lguConfig.seedAccounts.marketVendor4Email,
    "{{MARKET_COLLECTOR_EMAIL}}": lguConfig.seedAccounts.marketCollectorEmail,
    "{{MARKET_VENDOR_1_NAME}}": lguConfig.seedNames.marketVendor1,
    "{{MARKET_VENDOR_2_NAME}}": lguConfig.seedNames.marketVendor2,
    "{{MARKET_VENDOR_3_NAME}}": lguConfig.seedNames.marketVendor3,
    "{{MARKET_VENDOR_4_NAME}}": lguConfig.seedNames.marketVendor4,
    "{{MARKET_COLLECTOR_NAME}}": lguConfig.seedNames.marketCollector,
    "{{BARANGAY_NAME}}": lguConfig.barangays[0] ?? "{{BARANGAY_NAME}}",
};

export function sanitizeLguText(text: string | null | undefined): string {
    if (!text || typeof text !== "string") return "";
    return Object.entries(templateValues).reduce(
        (result, [placeholder, value]) => result.replaceAll(placeholder, value),
        text,
    );
}
